environment:
  matrix:
    - nodejs_version: "6.2.1"
    - nodejs_version: "6"
    - nodejs_version: "6.1"
    - nodejs_version: "5.11"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm test
version: 1.0.{build}
build: off
